### ISSUE TITLE
Install error with incompatible dependency and packages

### ISSUE THREAD

**Issue by tom832** [samgoldman97/mist-cf#3]
Great work !!

I have met some error when installing and running`. quickstart/run_model.sh`.

Can you give the entire packages list or detailed environment.yml file for us to follow the installation.

**Comment by samgoldman97** [comment]
Thanks for your interest in the work. Can you please be more specific? There is an environment/requirements file already included. One suggestion is to comment out the cudatoolkit version in the environment and see if it builds on cpu only.

**Comment by tom832** [comment]
> Thanks for your interest in the work. Can you please be more specific? There is an environment/requirements file already included. One suggestion is to comment out the cudatoolkit version in the environment and see if it builds on cpu only.

Thanks for reply. I have solve the issue. 
After mamba and pip installation, I need to downgrade these packages with pip:
`pytorch-lightning==1.4
ray-lightning==0.1.0
torchmetrics==0.5`

**Comment by tom832** [comment]
> Thanks for your interest in the work. Can you please be more specific? There is an environment/requirements file already included. One suggestion is to comment out the cudatoolkit version in the environment and see if it builds on cpu only.

Thanks for reply. I have solve the issue. 
After mamba and pip installation, I need to downgrade these packages with pip:
`pytorch-lightning==1.4
ray-lightning==0.1.0
torchmetrics==0.5`
